### ISSUE TITLE
SPIKE: MIP analysis config is parsed

### ISSUE THREAD

**Issue by ingkebil** [Clinical-Genomics/trailblazer#53]
Investigate if the `/home/proj/production/rare-disease/cases/justhusky/analysis_7.1/justhusky_qc_sample_info.yaml` can still be parsed by TB. Fix.

**Comment by barrystokman** [comment]
BS wil sit AJ to double check if all the right things are parsed.

**Comment by barrystokman** [comment]
This is investigated and fixed in https://github.com/Clinical-Genomics/trailblazer/pull/57

Parsing is used in storing analyses in housekeeper and uploading the results to scout: [cg_upload_scout_config.txt](https://zube.io/files/clinical-genomics/3dbc63c6124c9303821cd3f15aa94aa0-cg_upload_scout_config.txt)
[housekeeper_get_justhusky.txt](https://zube.io/files/clinical-genomics/7d8b08b65f46f543679a76e517eb33cd-housekeeper_get_justhusky.txt)
